const database = {
	tables: {
		chains: [
			{"cid":"2","name":"Cadena anterior de los brazos","image":require("@assets/Cadenas/CADENA_ANTERIOR_DE_LOS_BRAZOS.png")},
			{"cid":"3","name":"Cadena posterior de los brazos","image":require("@assets/Cadenas/CADENA_POSTERIOR_DE_LOS_BRAZOS.png")},
			{"cid":"4","name":"Cadena posterior superior","image":require("@assets/Cadenas/CADENA_POSTERIOR_SUPERIOR.png")},
			{"cid":"5","name":"Cadena posterior inferior","image":require("@assets/Cadenas/CADENA_POSTERIOR_INFERIOR.png")},
			{"cid":"6","name":"Cadena anterior","image":require("@assets/Cadenas/CADENA_ANTERIOR.png")},
			{"cid":"7","name":"Cuello","image":require("@assets/Cadenas/CUELLO.png")},
			{"cid":"8","name":"Cadena lateral","image":require("@assets/Cadenas/CADENA_LATERAL.png")}
		],
		exercises: [
			{"eid":"1" ,"showable":true ,"showableName":"Abrazarse", "name":"Abrazarse","description":"Este ejercicio se trata de simular un abrazo para que con la fuerza que hacemos con los dedos nos ayudemos a elongar la espalda.","gif":require("@assets/Ejercicios/ABRAZARSE.mp4"),"cid":"4"},
			{"eid":"2" ,"showable":true ,"showableName":"Alacrán (Bilateral)", "name":"Alacrán (Izquierda)","description":"Formando una T con los brazos y la pierna que va completamente extendida en el suelo llevamos el talón a la mano contralateral para elongar la parte inferior de la espalda.","gif":require("@assets/Ejercicios/ALACRAN.mp4"),"cid":"8"},
			{"eid":"3" ,"showable":false,"showableName":"Alacrán", "name":"Alacrán (Derecha)","description":"Formando una T con los brazos y la pierna que va completamente extendida en el suelo llevamos el talón a la mano contralateral para elongar la parte inferior de la espalda.","gif":require("@assets/Ejercicios/ALACRAN.mp4"),"cid":"8"},
			{"eid":"4" ,"showable":true ,"showableName":"Araña", "name":"Araña","description":"Este ejercicio se trata de empujar el suelo con las piernas y los brazos manteniendo el centro de gravedad en el centro de los apoyos y empujando la cadera al techo.","gif":require("@assets/Ejercicios/ARAÑA.mp4"),"cid":"6"},
			{"eid":"5" ,"showable":true ,"showableName":"Biceps pero con puño (Bilateral)", "name":"Biceps pero con puño (Izquierda)","description":"Este ejercicio se trata de apoyar el nudillo del índice en la pared con el brazo a 90° y luego hacer una rotación de tronco y cabeza.","gif":require("@assets/Ejercicios/BICEPS_PERO_CON_PUÑO.mp4"),"cid":"1"},
			{"eid":"6" ,"showable":false,"showableName":"Biceps pero con puño", "name":"Biceps pero con puño (Derecha)","description":"Este ejercicio se trata de apoyar el nudillo del índice en la pared con el brazo a 90° y luego hacer una rotación de tronco y cabeza.","gif":require("@assets/Ejercicios/BICEPS_PERO_CON_PUÑO.mp4"),"cid":"1"},
			{"eid":"7" ,"showable":true ,"showableName":"Bolita", "name":"Bolita","description":"Este ejercicio se trata de enrollarse acostado en el suelo con las piernas flexionadas relajando la espalda. Podes ayudarte apoyando los pies en la pared.","gif":require("@assets/Ejercicios/BOLITA.mp4"),"cid":"1"},
			{"eid":"8" ,"showable":true ,"showableName":"Cruz (Bilateral)", "name":"Cruz (Izquierda)","description":"Este ejercicio se trata de formar una T con los brazos y la pierna que va completamente extendida en el suelo, cruzando una pierna extendida en un ángulo en donde la tensión se sienta en glúteo o espalda baja.","gif":require("@assets/Ejercicios/CRUZ.mp4"),"cid":"8"},
			{"eid":"9" ,"showable":false,"showableName":"Cruz", "name":"Cruz (Derecha)","description":"Este ejercicio se trata de formar una T con los brazos y la pierna que va completamente extendida en el suelo, cruzando una pierna extendida en un ángulo en donde la tensión se sienta en glúteo o espalda baja.","gif":require("@assets/Ejercicios/CRUZ.mp4"),"cid":"8"},
			{"eid":"10","showable":true ,"showableName":"Cruzar manos atrás (Bilateral)", "name":"Cruzar mano atrás (Izquierda)","description":"Este ejercicio se trata de cruzar las manos por detrás del respaldar de una silla para inmovilizar el tronco y dejar caer la cabeza hacia atrás y un costado, la tensión se siente en los músculos del cuello.","gif":require("@assets/Ejercicios/CRUZAR_MANOS_ATRAS.mp4"),"cid":"1"},
			{"eid":"11","showable":false,"showableName":"Cruzar manos atrás", "name":"Cruzar mano atrás (Derecha)","description":"Este ejercicio se trata de cruzar las manos por detrás del respaldar de una silla para inmovilizar el tronco y dejar caer la cabeza hacia atrás y un costado, la tensión se siente en los músculos del cuello.","gif":require("@assets/Ejercicios/CRUZAR_MANOS_ATRAS.mp4"),"cid":"1"},
			{"eid":"12","showable":true ,"showableName":"Cruzar un palo (Bilateral)", "name":"Cruzar un palo (Izquierda)","description":"En este ejercicio utilizamos la ayuda de un bastón, con ambas manos tomamos los extremos y sin soltarlo realizamos un giro de 180°. Se debe sentir tensión en la espalda.","gif":require("@assets/Ejercicios/CRUZAR_UN_PALO.mp4"),"cid":"3"},
			{"eid":"13","showable":false,"showableName":"Cruzar un palo", "name":"Cruzar un palo (Derecha)","description":"En este ejercicio utilizamos la ayuda de un bastón, con ambas manos tomamos los extremos y sin soltarlo realizamos un giro de 180°. Se debe sentir tensión en la espalda.","gif":require("@assets/Ejercicios/CRUZAR_UN_PALO.mp4"),"cid":"3"},
			{"eid":"14","showable":true ,"showableName":"Cuadriceps levantado el talón (Bilateral)", "name":"Cuadriceps levantado el talón (Izquierda)","description":"Este ejercicio se trata de tener una pierna con flexión de cadera y rodilla a 90° y la otra apoyando la rodilla en el suelo, acto seguido se deja caer la cadera hacia delante sin inclinar el tronco y por último levantar el talón suavemente con loa mano o con ayuda de una soga.","gif":require("@assets/Ejercicios/CUADRICEPS_LEVANTADO_EL_TALON.mp4"),"cid":"6"},
			{"eid":"15","showable":false,"showableName":"Cuadriceps levantado el talón", "name":"Cuadriceps levantado el talón (Derecha)","description":"Este ejercicio se trata de tener una pierna con flexión de cadera y rodilla a 90° y la otra apoyando la rodilla en el suelo, acto seguido se deja caer la cadera hacia delante sin inclinar el tronco y por último levantar el talón suavemente con loa mano o con ayuda de una soga.","gif":require("@assets/Ejercicios/CUADRICEPS_LEVANTADO_EL_TALON.mp4"),"cid":"6"},
			{"eid":"16","showable":true ,"showableName":"Cuadriceps parado (Bilateral)", "name":"Cuadriceps parado (Izquierda)","description":"Este ejercicio se trata de alinear el tobillo, las rodillas, la cadera y los hombros en una misma línea vertical y llevar el talón hacia la cola mientras se hace una contracción del glúteo.","gif":require("@assets/Ejercicios/CUADRICEPS_PARADO.mp4"),"cid":"1"},
			{"eid":"17","showable":false,"showableName":"Cuadriceps parado", "name":"Cuadriceps parado (Derecha)","description":"Este ejercicio se trata de alinear el tobillo, las rodillas, la cadera y los hombros en una misma línea vertical y llevar el talón hacia la cola mientras se hace una contracción del glúteo.","gif":require("@assets/Ejercicios/CUADRICEPS_PARADO.mp4"),"cid":"1"},
			{"eid":"18","showable":true ,"showableName":"Dorsales sentado (Bilateral)", "name":"Dorsales sentado (Izquierda)","description":"Este ejercicio se trata de sentarse en una silla, tomar aire, levantar un brazo y llevar el tronco al lateral sin despegar la cola de la silla.","gif":require("@assets/Ejercicios/DORSALES_SENTADO.mp4"),"cid":"8"},
			{"eid":"19","showable":false,"showableName":"Dorsales sentado", "name":"Dorsales sentado (Derecha)","description":"Este ejercicio se trata de sentarse en una silla, tomar aire, levantar un brazo y llevar el tronco al lateral sin despegar la cola de la silla.","gif":require("@assets/Ejercicios/DORSALES_SENTADO.mp4"),"cid":"8"},
			{"eid":"20","showable":true ,"showableName":"Dorsales Y bastón (Bilateral)", "name":"Dorsales Y bastón (Izquierda)","description":"Este ejercicio se trata de tomar un bastón, empujarlo hacia el techo con los codos trabados e inclinarlos hasta formar una L con los brazos sin inclinar la cadera y el tronco.","gif":require("@assets/Ejercicios/DORSALES_Y_BASTON.mp4"),"cid":"1"},
			{"eid":"21","showable":false,"showableName":"Dorsales Y bastón", "name":"Dorsales Y bastón (Derecha)","description":"Este ejercicio se trata de tomar un bastón, empujarlo hacia el techo con los codos trabados e inclinarlos hasta formar una L con los brazos sin inclinar la cadera y el tronco.","gif":require("@assets/Ejercicios/DORSALES_Y_BASTON.mp4"),"cid":"1"},
			{"eid":"22","showable":true ,"showableName":"Enrollarse como una bolita", "name":"Enrollarse como una bolita","description":"Este ejercicio consta de 3 pasos. El primero es llevar la cabeza hacia atrás. El segundo paso es mirar al suelo sin inclinar el tronco. El tercer paso es flexionar el tronco lo que más puedas con el mentón cerca del pecho y los brazos colando.","gif":require("@assets/Ejercicios/ENROLLARSE_COMO_UNA_BOLITA.mp4"),"cid":"4"},
			{"eid":"23","showable":true ,"showableName":"Entrecruzar pulgares", "name":"Entrecruzar pulgares","description":"Este ejercicio se trata de apoyar los dedos en una silla con los pulgares entrecruzados y los brazos extendidos. Se debe sentir la tensión en antebrazos, palmas y dedos.","gif":require("@assets/Ejercicios/ENTRECRUZAR_PULGARES.mp4"),"cid":"2"},
			{"eid":"24","showable":true ,"showableName":"Flexor de cadera (Bilateral)", "name":"Flexor de cadera (Izquierda)","description":"Este ejercicio se trata de tener una pierna con flexión de cadera y rodilla a 90° y la otra apoyando la rodilla en el suelo, acto seguido se deja caer la cadera hacia delante y luego manteniendo la cadera en ese lugar inclinar el tronco hacia atrás.","gif":require("@assets/Ejercicios/FLEXOR_DE_CADERA.mp4"),"cid":"1"},
			{"eid":"25","showable":false,"showableName":"Flexor de cadera", "name":"Flexor de cadera (Derecha)","description":"Este ejercicio se trata de tener una pierna con flexión de cadera y rodilla a 90° y la otra apoyando la rodilla en el suelo, acto seguido se deja caer la cadera hacia delante y luego manteniendo la cadera en ese lugar inclinar el tronco hacia atrás.","gif":require("@assets/Ejercicios/FLEXOR_DE_CADERA.mp4"),"cid":"1"},
			{"eid":"26","showable":true ,"showableName":"Gemelos con soga (Bilateral)", "name":"Gemelos con soga (Izquierda)","description":"Este ejercicio se trata de que con la ayuda de una soga tiremos de la punta del pie hacia arriba.","gif":require("@assets/Ejercicios/GEMELOS_CON_SOGA.mp4"),"cid":"1"},
			{"eid":"27","showable":false,"showableName":"Gemelos con soga", "name":"Gemelos con soga (Derecha)","description":"Este ejercicio se trata de que con la ayuda de una soga tiremos de la punta del pie hacia arriba.","gif":require("@assets/Ejercicios/GEMELOS_CON_SOGA.mp4"),"cid":"1"},
			{"eid":"28","showable":true ,"showableName":"Gemelos parado (Bilateral)", "name":"Gemelos parado (Izquierda)","description":"Se trata de pisar un taco de aproximadamente 8 cm con la punta del pie y la rodilla extendida. Si no sentís tanta tensión en el gemelo podés adelantar la cadera sin perder la extensión de la rodilla.","gif":require("@assets/Ejercicios/GEMELOS_PARADO.mp4"),"cid":"1"},
			{"eid":"29","showable":false,"showableName":"Gemelos parado", "name":"Gemelos parado (Derecha)","description":"Se trata de pisar un taco de aproximadamente 8 cm con la punta del pie y la rodilla extendida. Si no sentís tanta tensión en el gemelo podés adelantar la cadera sin perder la extensión de la rodilla.","gif":require("@assets/Ejercicios/GEMELOS_PARADO.mp4"),"cid":"1"},
			{"eid":"30","showable":true ,"showableName":"Glúteo abrazar la rodilla (Bilateral)", "name":"Glúteo abrazar la rodilla (Izquierda)","description":"Este ejercicio se trata de cruzar una pierna flexionada y acercarla al pecho manteniendo la espalda recta.","gif":require("@assets/Ejercicios/GLUTEO_ABRAZAR_LA_RODILLA.mp4"),"cid":"1"},
			{"eid":"31","showable":false,"showableName":"Glúteo abrazar la rodilla", "name":"Glúteo abrazar la rodilla (Derecha)","description":"Este ejercicio se trata de cruzar una pierna flexionada y acercarla al pecho manteniendo la espalda recta.","gif":require("@assets/Ejercicios/GLUTEO_ABRAZAR_LA_RODILLA.mp4"),"cid":"1"},
			{"eid":"32","showable":true ,"showableName":"El 4 (Bilateral)", "name":"El 4 (Izquierda)","description":"Este ejercicio tiene 2 pasos. El primero es apoyar la espalda contra la pared y cruzar el talón sobre la rodilla. El segundo paso es bajar lentamente con la rodilla cerca del cuerpo hasta unos cm antes de que se despegue el talón del pie que está en el piso.","gif":require("@assets/Ejercicios/EL_4.mp4"),"cid":"1"},
			{"eid":"33","showable":false,"showableName":"El 4", "name":"El 4 (Derecha)","description":"Este ejercicio tiene 2 pasos. El primero es apoyar la espalda contra la pared y cruzar el talón sobre la rodilla. El segundo paso es bajar lentamente con la rodilla cerca del cuerpo hasta unos cm antes de que se despegue el talón del pie que está en el piso.","gif":require("@assets/Ejercicios/EL_4.mp4"),"cid":"1"},
			{"eid":"34","showable":true ,"showableName":"Hombros cara posterior", "name":"Hombros cara posterior","description":"Este ejercicio se trata de formar un ángulo de 90° empujando con el pecho hacia el suelo. Se siente tensión en pectoral y brazos.","gif":require("@assets/Ejercicios/HOMBROS_CARA_POSTERIOR.mp4"),"cid":"1"},
			{"eid":"35","showable":true,"showableName":"Hombros cara anterior", "name":"Hombros cara anterior","description":"Este ejercicio se trata de sentare en el suelo apoyar las manos con los dedos apuntando hacia atrás e ir caminando con los dedos hacia atrás. Se debe sentir tensión en los hombros.","gif":require("@assets/Ejercicios/HOMBROS_CARA_ANTERIOR.mp4"),"cid":"1"},
			{"eid":"36","showable":true ,"showableName":"Isquio adaptado", "name":"Isquio adaptado","description":"Este ejercicio se trata de pararse a menos de un paso de frente a la pared y apoyar la espalda contra ella sin perder la extensión de las rodillas.","gif":require("@assets/Ejercicios/ISQUIO_ADAPTADO.mp4"),"cid":"1"},
			{"eid":"37","showable":true ,"showableName":"Isquio con soga sentado", "name":"Isquio con soga sentado","description":"Este ejercicio se trata de sentarse en el suelo e inclinar el tronco hacia adelante sin flexionarlo con la ayuda de una soga.","gif":require("@assets/Ejercicios/ISQUIO_CON_SOGA_SENTADO.mp4"),"cid":"1"},
			{"eid":"38","showable":true ,"showableName":"Isquio tirar del pie (Bilateral)", "name":"Isquio tirar del pie (Izquierda)","description":"Acostado en el suelo levantas una pierna extendida con la ayuda de una soga.","gif":require("@assets/Ejercicios/ISQUIO_TIRAR_DEL_PIE.mp4"),"cid":"1"},
			{"eid":"39","showable":false,"showableName":"Isquio tirar del pie", "name":"Isquio tirar del pie (Derecha)","description":"Acostado en el suelo levantas una pierna extendida con la ayuda de una soga.","gif":require("@assets/Ejercicios/ISQUIO_TIRAR_DEL_PIE.mp4"),"cid":"1"},
			{"eid":"40","showable":true ,"showableName":"Rezar", "name":"Rezar","description":"Este ejercicio se trata de juntar el dorso de las manos a la altura del pecho y descenderlas hasta antes de que se separen. La tensión se siente en antebrazo.","gif":require("@assets/Ejercicios/REZAR.mp4"),"cid":"1"},
			{"eid":"41","showable":true ,"showableName":"Juntar plantas", "name":"Juntar plantas","description":"Este ejercicio se trata de sentarse, juntar las plantas de los pies, acercándolas lo más posible y con los codos empujar las piernas hacia abajo.","gif":require("@assets/Ejercicios/JUNTAR_PLANTAS.mp4"),"cid":"1"},
			{"eid":"42","showable":true ,"showableName":"Saludo al sol parado", "name":"Saludo al sol parado","description":"Este ejercicio se trata de inclinar el tronco y la cabeza hacia atrás manteniendo las rodillas extendidas.","gif":require("@assets/Ejercicios/SALUDO_AL_SOL_PARADO.mp4"),"cid":"6"},
			{"eid":"43","showable":true ,"showableName":"Mano a la axila (Bilateral)", "name":"Mano a la axila (Izquierda)","description":"Este ejercicio se trata de cruzar una mano por debajo de la axila y con la otra mano empujar desde el codo para alargar su recorrido. Se debe sentir tensión en hombro y espalda.","gif":require("@assets/Ejercicios/MANO_A_LA_AXILA.mp4"),"cid":"3"},
			{"eid":"44","showable":false,"showableName":"Mano a la axila", "name":"Mano a la axila (Derecha)","description":"Este ejercicio se trata de cruzar una mano por debajo de la axila y con la otra mano empujar desde el codo para alargar su recorrido. Se debe sentir tensión en hombro y espalda.","gif":require("@assets/Ejercicios/MANO_A_LA_AXILA.mp4"),"cid":"3"},
			{"eid":"45","showable":true ,"showableName":"Mano en el cuello", "name":"Mano en el cuello","description":"Este ejercicio se trata de flexionar el cuello con la ayuda de las manos.","gif":require("@assets/Ejercicios/MANO_EN_EL_CUELLO.mp4"),"cid":"7"},
			{"eid":"46","showable":true ,"showableName":"Mansalva", "name":"Mansalva","description":"Sentado en una silla, hacer una inspiración profunda mantenida y hacer flexión de tronco.","gif":require("@assets/Ejercicios/MANSALVA.mp4"),"cid":"7"},
			{"eid":"47","showable":true ,"showableName":"Mástil (Bilateral)", "name":"Mástil (Izquierda)","description":"Este ejercicio se trata de hacer una sentadilla profunda sumándole una rotación de tronco y ayudándonos con un peso que vamos a tener en nuestro brazo completamente extendido.","gif":require("@assets/Ejercicios/MASTIL.mp4"),"cid":"1"},
			{"eid":"48","showable":false,"showableName":"Mástil", "name":"Mástil (Derecha)","description":"Este ejercicio se trata de hacer una sentadilla profunda sumándole una rotación de tronco y ayudándonos con un peso que vamos a tener en nuestro brazo completamente extendido.","gif":require("@assets/Ejercicios/MASTIL.mp4"),"cid":"1"},
			{"eid":"49","showable":true ,"showableName":"Monje", "name":"Monje","description":"Este ejercicio se trata de sentarnos sobre nuestros talones apoyando los empeines en el suelo.","gif":require("@assets/Ejercicios/MONJE.mp4"),"cid":"1"},
			{"eid":"50","showable":true ,"showableName":"Canastita acostado (Bilateral)", "name":"Canastita acostado (Izquierda)","description":"Este ejercicio consta de 2 pasos. El primero es sentarse en canastita y el segundo es con un almohadón que me ayude a elevar la cadera, recostarme y tratar de llevar las rodillas hacia el suelo.","gif":require("@assets/Ejercicios/CANASTITA_ACOSTADO.mp4"),"cid":"6"},
			{"eid":"51","showable":false,"showableName":"Canastita acostado", "name":"Canastita acostado (Derecha)","description":"Este ejercicio consta de 2 pasos. El primero es sentarse en canastita y el segundo es con un almohadón que me ayude a elevar la cadera, recostarme y tratar de llevar las rodillas hacia el suelo.","gif":require("@assets/Ejercicios/CANASTITA_ACOSTADO.mp4"),"cid":"6"},
			{"eid":"52","showable":true ,"showableName":"Pectoral a 120 (Bilateral)", "name":"Pectoral a 120 (Izquierda)","description":"Este ejercicio se trata de extender un brazo a 120° con la mano apoyada sobre loa pared y realizar una rotación.","gif":require("@assets/Ejercicios/PECTORAL_A_120.mp4"),"cid":"1"},
			{"eid":"53","showable":false,"showableName":"Pectoral a 120", "name":"Pectoral a 120 (Derecha)","description":"Este ejercicio se trata de extender un brazo a 120° con la mano apoyada sobre loa pared y realizar una rotación.","gif":require("@assets/Ejercicios/PECTORAL_A_120.mp4"),"cid":"1"},
			{"eid":"54","showable":true ,"showableName":"Pectoral con bastón", "name":"Pectoral con bastón","description":"Este ejercicio se trata de tomar un bastón y con los codos trabados llevarlo hacia atrás hasta la altura del pectoral. El ancho del agarre va a estar delimitado por tu flexibilidad.","gif":require("@assets/Ejercicios/PECTORAL_CON_BASTON.mp4"),"cid":"2"},
			{"eid":"55","showable":true ,"showableName":"Pectoral en la pared (Bilateral)", "name":"Pectoral en la pared (Izquierda)","description":"Este ejercicio se trata de extender un brazo a 90° con la mano apoyada sobre loa pared y realizar una rotación.","gif":require("@assets/Ejercicios/PECTORAL_EN_LA_PARED.mp4"),"cid":"1"},
			{"eid":"56","showable":false,"showableName":"Pectoral en la pared", "name":"Pectoral en la pared (Derecha)","description":"Este ejercicio se trata de extender un brazo a 90° con la mano apoyada sobre loa pared y realizar una rotación.","gif":require("@assets/Ejercicios/PECTORAL_EN_LA_PARED.mp4"),"cid":"1"},
			{"eid":"57","showable":true ,"showableName":"Isquio parado (Bilateral)", "name":"Isquio parado (Izquierda)","description":"Este ejercicio tiene dos pasos. El primero es apoyar el pie en una superficie más alta que tus rodillas y luego inclinar el tronco completamente erguido.","gif":require("@assets/Ejercicios/ISQUIO_PARADO.mp4"),"cid":"5"},
			{"eid":"58","showable":false,"showableName":"Isquio parado", "name":"Isquio parado (Derecha)","description":"Este ejercicio tiene dos pasos. El primero es apoyar el pie en una superficie más alta que tus rodillas y luego inclinar el tronco completamente erguido.","gif":require("@assets/Ejercicios/ISQUIO_PARADO.mp4"),"cid":"5"},
			{"eid":"59","showable":true ,"showableName":"Plantares (Bilateral)", "name":"Plantares (Izquierda)","description":"Este ejercicio se trata de separar los dedos del pie como un abanico y tirarlos hacia tu lado.","gif":require("@assets/Ejercicios/PLANTARES.mp4"),"cid":"1"},
			{"eid":"60","showable":false,"showableName":"Plantares", "name":"Plantares (Derecha)","description":"Este ejercicio se trata de separar los dedos del pie como un abanico y tirarlos hacia tu lado.","gif":require("@assets/Ejercicios/PLANTARES.mp4"),"cid":"1"},
			{"eid":"61","showable":true ,"showableName":"Pronación máxima (Bilateral)", "name":"Pronación máxima (Izquierda)","description":"Este ejercicio se trata de apoyar el dorso de la mano en la pared con el brazo extendido y realizar una rotación de aproximadamente 360° en el sentido antihorario. La tensión se siente en el antebrazo.","gif":require("@assets/Ejercicios/PRONACION_MAXIMA.mp4"),"cid":"1"},
			{"eid":"62","showable":false,"showableName":"Pronación máxima", "name":"Pronación máxima (Derecha)","description":"Este ejercicio se trata de apoyar el dorso de la mano en la pared con el brazo extendido y realizar una rotación de aproximadamente 360° en el sentido antihorario. La tensión se siente en el antebrazo.","gif":require("@assets/Ejercicios/PRONACION_MAXIMA.mp4"),"cid":"1"},
			{"eid":"63","showable":true ,"showableName":"Puños al piso", "name":"Puños al piso","description":"Este ejercicio se trata de apoyar ambos puños en el piso y dejar caer las muñecas hacia los laterales.","gif":require("@assets/Ejercicios/PUÑOS_AL_PISO.mp4"),"cid":"3"},
			{"eid":"64","showable":true ,"showableName":"Cruz en L (Bilateral)", "name":"Cruz en L (Izquierda)","description":"Este ejercicio se trata de formar una T con los brazos y la pierna que va completamente extendida en el suelo, cruzando una pierna con una flexión de rodilla de 90°.","gif":require("@assets/Ejercicios/CRUZ_EN_L.mp4"),"cid":"1"},
			{"eid":"65","showable":false,"showableName":"Cruz en L", "name":"Cruz en L (Derecha)","description":"Este ejercicio se trata de formar una T con los brazos y la pierna que va completamente extendida en el suelo, cruzando una pierna con una flexión de rodilla de 90°.","gif":require("@assets/Ejercicios/CRUZ_EN_L.mp4"),"cid":"1"},
			{"eid":"66","showable":true ,"showableName":"Rotadores (Bilateral)", "name":"Rotadores (Izquierda)","description":"Este ejercicio se trata de sentado en una silla, ayudarse con el respaldar de la misma hacer una rotación de tronco y cabeza.","gif":require("@assets/Ejercicios/ROTADORES.mp4"),"cid":"1"},
			{"eid":"67","showable":false,"showableName":"Rotadores", "name":"Rotadores (Derecha)","description":"Este ejercicio se trata de sentado en una silla, ayudarse con el respaldar de la misma hacer una rotación de tronco y cabeza.","gif":require("@assets/Ejercicios/ROTADORES.mp4"),"cid":"1"},
			{"eid":"68","showable":true ,"showableName":"Saludo al sol", "name":"Saludo al sol","description":"Acostado boca abajo empujar con los brazos hacia arriba y hacia atrás, acompañando el movimiento con la cabeza y apenas despegando la cadera.","gif":require("@assets/Ejercicios/SALUDO_AL_SOL.mp4") ,"cid":"1"},
			{"eid":"69","showable":true ,"showableName":"Sentarse en el talón (Bilateral)", "name":"Sentarse en el talón (Izquierda)","description":"Este ejercicio se trata de sentarse en un talón mientras que la otra pierna queda extendida hacia adelante contrayendo los glúteos. La tensión se debe sentir en la cara anterior del muslo.","gif":require("@assets/Ejercicios/SENTARSE_EN_EL_TALON.mp4"),"cid":"1"},
			{"eid":"70","showable":false,"showableName":"Sentarse en el talón", "name":"Sentarse en el talón (Derecha)","description":"Este ejercicio se trata de sentarse en un talón mientras que la otra pierna queda extendida hacia adelante contrayendo los glúteos. La tensión se debe sentir en la cara anterior del muslo.","gif":require("@assets/Ejercicios/SENTARSE_EN_EL_TALON.mp4"),"cid":"1"},
			{"eid":"71","showable":true ,"showableName":"Sóleo (Bilateral)", "name":"Sóleo (Izquierda)","description":"Este ejercicio se trata de pisar un taco de aproximadamente 8 cm con la punta del pie, el talón apoyado en el suelo en todo momento y con la rodilla flexionada. Podes ayudarte con las manos para empujar la rodilla hacia delante y sentir tensión entre el talón y la pantorrilla.","gif":require("@assets/Ejercicios/SOLEO.mp4"),"cid":"1"},
			{"eid":"72","showable":false,"showableName":"Sóleo", "name":"Sóleo (Derecha)","description":"Este ejercicio se trata de pisar un taco de aproximadamente 8 cm con la punta del pie, el talón apoyado en el suelo en todo momento y con la rodilla flexionada. Podes ayudarte con las manos para empujar la rodilla hacia delante y sentir tensión entre el talón y la pantorrilla.","gif":require("@assets/Ejercicios/SOLEO.mp4"),"cid":"1"},
			{"eid":"73","showable":true ,"showableName":"Dedos al medio", "name":"Dedos al medio","description":"Este ejercicio se trata de apoyar la punta de los dedos en un taco de aproximadamente 8 cm y el talón de la mano en el suelo hacia afuera con los brazos totalmente extendidos.","gif":require("@assets/Ejercicios/DEDOS_AL_MEDIO.mp4"),"cid":"1"},
			{"eid":"74","showable":true ,"showableName":"TFL empujando la rodilla (Bilateral)", "name":"TFL empujando la rodilla (Izquierda)","description":"Este ejercicio se trata de tener una pierna con flexión de cadera y rodilla a 90° y la otra apoyando la rodilla en el suelo, luego apoyar ambas manos en el suelo y con el codo empujar la rodilla hacia afuera.","gif":require("@assets/Ejercicios/TFL_EMPUJANDO_LA_RODILLA.mp4"),"cid":"1"},
			{"eid":"75","showable":false,"showableName":"TFL empujando la rodilla", "name":"TFL empujando la rodilla (Derecha)","description":"Este ejercicio se trata de tener una pierna con flexión de cadera y rodilla a 90° y la otra apoyando la rodilla en el suelo, luego apoyar ambas manos en el suelo y con el codo empujar la rodilla hacia afuera.","gif":require("@assets/Ejercicios/TFL_EMPUJANDO_LA_RODILLA.mp4"),"cid":"1"},
			{"eid":"76","showable":true ,"showableName":"TFL parado (Bilateral)", "name":"TFL parado (Izquierda)","description":"Este ejercicio se trata de tener una pierna con flexión de cadera y rodilla a 90° y la otra apoyando la rodilla en el suelo cruzar una pierna sobre la otra de manera que la que está por detrás quede con la planta del pie sin tocar el suelo y tocar el suelo con las manos.","gif":require("@assets/Ejercicios/TFL_PARADO.mp4"),"cid":"1"},
			{"eid":"77","showable":false,"showableName":"TFL parado", "name":"TFL parado (Derecha)","description":"Este ejercicio se trata de tener una pierna con flexión de cadera y rodilla a 90° y la otra apoyando la rodilla en el suelo cruzar una pierna sobre la otra de manera que la que está por detrás quede con la planta del pie sin tocar el suelo y tocar el suelo con las manos.","gif":require("@assets/Ejercicios/TFL_PARADO.mp4"),"cid":"1"},
			{"eid":"78","showable":true ,"showableName":"Rodilla afuera (Bilateral)", "name":"Rodilla afuera (Izquierda)","description":"Este ejercicio se trata de apoyar la punta del pie en un taco de aproximadamente 8 cm, el talón en el suelo, flexionar la rodilla y llevarla hacia afuera y hacia adelante. Mientras tanto la otra pierna queda de apoyo un paso hacia atrás.","gif":require("@assets/Ejercicios/RODILLA_AFUERA.mp4"),"cid":"1"},
			{"eid":"79","showable":false,"showableName":"Rodilla afuera", "name":"Rodilla afuera (Derecha)","description":"Este ejercicio se trata de apoyar la punta del pie en un taco de aproximadamente 8 cm, el talón en el suelo, flexionar la rodilla y llevarla hacia afuera y hacia adelante. Mientras tanto la otra pierna queda de apoyo un paso hacia atrás.","gif":require("@assets/Ejercicios/RODILLA_AFUERA.mp4"),"cid":"1"},
			{"eid":"80","showable":true ,"showableName":"Tirarse dedos para atrás (Bilateral)", "name":"Tirarse dedos para atrás (Izquierda)","description":"Este ejercicio se trata de extender un brazo hacia adelante y con la otra mano tirar los dedos hacia tu lado.","gif":require("@assets/Ejercicios/TIRARSE_DEDOS_PARA_ATRAS.mp4"),"cid":"2"},
			{"eid":"81","showable":false,"showableName":"Tirarse dedos para atrás", "name":"Tirarse dedos para atrás (Derecha)","description":"Este ejercicio se trata de extender un brazo hacia adelante y con la otra mano tirar los dedos hacia tu lado.","gif":require("@assets/Ejercicios/TIRARSE_DEDOS_PARA_ATRAS.mp4"),"cid":"2"},
			{"eid":"82","showable":true ,"showableName":"Trapecio sentado (Bilateral)", "name":"Trapecio sentado (Izquierda)","description":"Sentado en una silla, tomarse del asiento e inclinar la cabeza hacia el lado contrario.","gif":require("@assets/Ejercicios/TRAPECIO_SENTADO.mp4"),"cid":"1"},
			{"eid":"83","showable":false,"showableName":"Trapecio sentado", "name":"Trapecio sentado (Derecha)","description":"Sentado en una silla, tomarse del asiento e inclinar la cabeza hacia el lado contrario.","gif":require("@assets/Ejercicios/TRAPECIO_SENTADO.mp4"),"cid":"1"},
			{"eid":"84","showable":true ,"showableName":"Triángulo de cadera (Bilateral)", "name":"Triángulo de cadera (Izquierda)","description":"Este ejercicio se trata de pisar con un solo pie un taco de aproximadamente 8 cm y con ambas piernas extendidas llevar las manos al suelo.","gif":require("@assets/Ejercicios/TRIANGULO_DE_CADERA.mp4"),"cid":"5"},
			{"eid":"85","showable":false,"showableName":"Triángulo de cadera", "name":"Triángulo de cadera (Derecha)","description":"Este ejercicio se trata de pisar con un solo pie un taco de aproximadamente 8 cm y con ambas piernas extendidas llevar las manos al suelo.","gif":require("@assets/Ejercicios/TRIANGULO_DE_CADERA.mp4"),"cid":"5"},
			{"eid":"86","showable":true ,"showableName":"Triceps (Bilateral)", "name":"Triceps (Izquierda)","description":"Este ejercicio se trata de llevar la palma de la mano hacia la espalda y, sin inclinar el tronco, empujarse desde el codo con la mano contralateral para alargar el recorrido de la misma.","gif":require("@assets/Ejercicios/TRICEPS.mp4"),"cid":"1"},
			{"eid":"87","showable":false,"showableName":"Triceps", "name":"Triceps (Derecha)","description":"Este ejercicio se trata de llevar la palma de la mano hacia la espalda y, sin inclinar el tronco, empujarse desde el codo con la mano contralateral para alargar el recorrido de la misma.","gif":require("@assets/Ejercicios/TRICEPS.mp4"),"cid":"1"},
			{"eid":"88","showable":true ,"showableName":"Y (Bilateral)", "name":"Y (Izquierda)","description":"Este ejercicio se trata de tomar un bastón, empujarlo perpendicularmente hacia arriba e inclinar el tronco y la cabeza manteniendo la cadera fija.","gif":require("@assets/Ejercicios/Y.mp4"),"cid":"1"},
			{"eid":"89","showable":false,"showableName":"Y", "name":"Y (Derecha)","description":"Este ejercicio se trata de tomar un bastón, empujarlo perpendicularmente hacia arriba e inclinar el tronco y la cabeza manteniendo la cadera fija.","gif":require("@assets/Ejercicios/Y.mp4"),"cid":"1"},
			{"eid":"90","showable":true ,"showableName":"Zapo", "name":"Zapo","description":"Este ejercicio se trata de arrodillarse con las manos apoyadas en el suelo y un ancho de rodillas que te permita llevar tu cadera hacia el lado de tus talones tratando de mantener la columna erguida.","gif":require("@assets/Ejercicios/ZAPO.mp4"),"cid":"1"},
		],
		exercises_routines: [
			//GENERAL
			{"erid":"1","rid":"4","eid":"68"},
			{"erid":"2","rid":"4","eid":"7"},
			{"erid":"3","rid":"4","eid":"30"},
			{"erid":"4","rid":"4","eid":"31"},
			{"erid":"5","rid":"4","eid":"37"},
			{"erid":"6","rid":"4","eid":"26"},
			{"erid":"7","rid":"4","eid":"27"},
			{"erid":"8","rid":"4","eid":"49"},
			{"erid":"9","rid":"4","eid":"59"},
			{"erid":"10","rid":"4","eid":"60"},
			{"erid":"11","rid":"4","eid":"71"},
			{"erid":"12","rid":"4","eid":"72"},
			{"erid":"13","rid":"4","eid":"41"},
			{"erid":"14","rid":"4","eid":"90"},
			{"erid":"15","rid":"4","eid":"76"},
			{"erid":"16","rid":"4","eid":"77"},
			{"erid":"17","rid":"4","eid":"24"},
			{"erid":"18","rid":"4","eid":"25"},
			{"erid":"19","rid":"4","eid":"16"},
			{"erid":"20","rid":"4","eid":"17"},
			{"erid":"21","rid":"4","eid":"88"},
			{"erid":"22","rid":"4","eid":"89"},
			{"erid":"23","rid":"4","eid":"34"},
			{"erid":"24","rid":"4","eid":"35"},
			{"erid":"25","rid":"4","eid":"55"},
			{"erid":"26","rid":"4","eid":"56"},
			{"erid":"27","rid":"4","eid":"86"},
			{"erid":"28","rid":"4","eid":"87"},
			{"erid":"29","rid":"4","eid":"82"},
			{"erid":"30","rid":"4","eid":"83"},
			//RUBGBY
			{"erid":"31","rid":"17","eid":"36"},
			{"erid":"32","rid":"17","eid":"69"},
			{"erid":"33","rid":"17","eid":"70"},
			{"erid":"34","rid":"17","eid":"90"},
			{"erid":"35","rid":"17","eid":"35"},
			{"erid":"36","rid":"17","eid":"66"},
			{"erid":"37","rid":"17","eid":"67"},
			{"erid":"38","rid":"17","eid":"7"},
			//TENIS
			{"erid":"39","rid":"11","eid":"54"},
			{"erid":"40","rid":"11","eid":"80"},
			{"erid":"41","rid":"11","eid":"81"},
			{"erid":"42","rid":"11","eid":"40"},
			{"erid":"43","rid":"11","eid":"28"},
			{"erid":"44","rid":"11","eid":"29"},
			{"erid":"45","rid":"11","eid":"59"},
			{"erid":"46","rid":"11","eid":"60"},
			{"erid":"47","rid":"11","eid":"64"},
			{"erid":"48","rid":"11","eid":"65"},
			//BOXEO
			{"erid":"49","rid":"19","eid":"46"},
			{"erid":"50","rid":"19","eid":"54"},
			{"erid":"51","rid":"19","eid":"66"},
			{"erid":"52","rid":"19","eid":"67"},
			{"erid":"53","rid":"19","eid":"59"},
			{"erid":"54","rid":"19","eid":"60"},
			//LEVANTAMIENTO DE PESAS
			{"erid":"55","rid":"12","eid":"32"},
			{"erid":"56","rid":"12","eid":"33"},
			{"erid":"57","rid":"12","eid":"38"},
			{"erid":"58","rid":"12","eid":"39"},
			{"erid":"59","rid":"12","eid":"78"},
			{"erid":"60","rid":"12","eid":"79"},
			{"erid":"61","rid":"12","eid":"71"},
			{"erid":"62","rid":"12","eid":"72"},
			{"erid":"63","rid":"12","eid":"24"},
			{"erid":"64","rid":"12","eid":"25"},
			{"erid":"65","rid":"12","eid":"14"},
			{"erid":"66","rid":"12","eid":"15"},
			{"erid":"67","rid":"12","eid":"23"},
			{"erid":"68","rid":"12","eid":"47"},
			{"erid":"69","rid":"12","eid":"48"},
			//JUDO
			{"erid":"70","rid":"18","eid":"18"},
			{"erid":"71","rid":"18","eid":"19"},
			{"erid":"72","rid":"18","eid":"7"},
			{"erid":"73","rid":"18","eid":"5"},
			{"erid":"74","rid":"18","eid":"6"},
			{"erid":"75","rid":"18","eid":"86"},
			{"erid":"76","rid":"18","eid":"87"},
			{"erid":"77","rid":"18","eid":"14"},
			{"erid":"78","rid":"18","eid":"15"},
			{"erid":"79","rid":"18","eid":"23"},
			//VOLEY
			{"erid":"80","rid":"13","eid":"61"},
			{"erid":"81","rid":"13","eid":"62"},
			{"erid":"82","rid":"13","eid":"45"},
			{"erid":"83","rid":"13","eid":"7"},
			{"erid":"84","rid":"13","eid":"16"},
			{"erid":"85","rid":"13","eid":"17"},
			{"erid":"86","rid":"13","eid":"52"},
			{"erid":"87","rid":"13","eid":"53"},
			//BASQUET
			{"erid":"88","rid":"9","eid":"66"},
			{"erid":"89","rid":"9","eid":"67"},
			{"erid":"90","rid":"9","eid":"30"},
			{"erid":"91","rid":"9","eid":"31"},
			{"erid":"92","rid":"9","eid":"74"},
			{"erid":"93","rid":"9","eid":"75"},
			{"erid":"94","rid":"9","eid":"16"},
			{"erid":"95","rid":"9","eid":"17"},
			{"erid":"96","rid":"9","eid":"41"},
			{"erid":"97","rid":"9","eid":"7"},
			{"erid":"98","rid":"9","eid":"28"},
			{"erid":"99","rid":"9","eid":"29"},
			//HOCKEY
			{"erid":"100","rid":"8","eid":"1"},
			{"erid":"101","rid":"8","eid":"2"},
			{"erid":"102","rid":"8","eid":"3"},
			{"erid":"103","rid":"8","eid":"30"},
			{"erid":"104","rid":"8","eid":"31"},
			{"erid":"105","rid":"8","eid":"38"},
			{"erid":"106","rid":"8","eid":"39"},
			{"erid":"107","rid":"8","eid":"54"},
			{"erid":"108","rid":"8","eid":"28"},
			{"erid":"109","rid":"8","eid":"29"},
			{"erid":"110","rid":"8","eid":"45"},
			//POWER LIFTING
			{"erid":"111","rid":"16","eid":"7"},
			{"erid":"112","rid":"16","eid":"12"},
			{"erid":"113","rid":"16","eid":"13"},
			{"erid":"114","rid":"16","eid":"1"},
			{"erid":"115","rid":"16","eid":"54"},
			{"erid":"116","rid":"16","eid":"24"},
			{"erid":"117","rid":"16","eid":"25"},
			{"erid":"118","rid":"16","eid":"30"},
			{"erid":"119","rid":"16","eid":"31"},
			//NATACIÓN
			{"erid":"120","rid":"14","eid":"54"},
			{"erid":"121","rid":"14","eid":"73"},
			{"erid":"122","rid":"14","eid":"28"},
			{"erid":"123","rid":"14","eid":"29"},
			{"erid":"124","rid":"14","eid":"59"},
			{"erid":"125","rid":"14","eid":"60"},
			//CROSSFIT
			{"erid":"126","rid":"15","eid":"32"},
			{"erid":"127","rid":"15","eid":"33"},
			{"erid":"128","rid":"15","eid":"38"},
			{"erid":"129","rid":"15","eid":"39"},
			{"erid":"130","rid":"15","eid":"78"},
			{"erid":"131","rid":"15","eid":"79"},
			{"erid":"132","rid":"15","eid":"71"},
			{"erid":"133","rid":"15","eid":"72"},
			{"erid":"134","rid":"15","eid":"24"},
			{"erid":"135","rid":"15","eid":"25"},
			{"erid":"136","rid":"15","eid":"14"},
			{"erid":"137","rid":"15","eid":"15"},
			{"erid":"138","rid":"15","eid":"23"},
			{"erid":"139","rid":"15","eid":"47"},
			{"erid":"140","rid":"15","eid":"48"},
			//FUTBOL
			{"erid":"141","rid":"10","eid":"66"},
			{"erid":"142","rid":"10","eid":"67"},
			{"erid":"143","rid":"10","eid":"30"},
			{"erid":"144","rid":"10","eid":"31"},
			{"erid":"145","rid":"10","eid":"74"},
			{"erid":"146","rid":"10","eid":"75"},
			{"erid":"147","rid":"10","eid":"16"},
			{"erid":"148","rid":"10","eid":"17"},
			{"erid":"149","rid":"10","eid":"41"},
			{"erid":"150","rid":"10","eid":"7"},
			{"erid":"151","rid":"10","eid":"28"},
			{"erid":"152","rid":"10","eid":"29"}
		],
		routines: [
			{"rid":"4","type":"general","name":"General","sid":null},
			{"rid":"8","type":"sport","name":"Hockey","sid":"1"},
			{"rid":"9","type":"sport","name":"Básquet","sid":"2"},
			{"rid":"10","type":"sport","name":"Fútbol","sid":"3"},
			{"rid":"11","type":"sport","name":"Tenis","sid":"6"},
			{"rid":"12","type":"sport","name":"Levantamiento de pesas","sid":"7"},
			{"rid":"13","type":"sport","name":"Voley","sid":"8"},
			{"rid":"14","type":"sport","name":"Natación","sid":"9"},
			{"rid":"15","type":"sport","name":"Crossfit","sid":"10"},
			{"rid":"16","type":"sport","name":"Power lifting","sid":"11"},
			{"rid":"17","type":"sport","name":"Rugby","sid":"12"},
			{"rid":"18","type":"sport","name":"Judo","sid":"13"},
			{"rid":"19","type":"sport","name":"Boxeo","sid":"14"},
		],
		sports: [
			{"sid":"1","name":"Hockey"},
			{"sid":"2","name":"Básquet"},
			{"sid":"3","name":"Fútbol"},
			{"sid":"6","name":"Tenis"},
			{"sid":"7","name":"Levantamiento de pesas"},
			{"sid":"8","name":"Voley"},
			{"sid":"9","name":"Natación"},
			{"sid":"10","name":"Crossfit"},
			{"sid":"11","name":"Power lifting"},
			{"sid":"12","name":"Rugby"},
			{"sid":"13","name":"Judo"},
			{"sid":"14","name":"Boxeo"}
		]
	}
}

export default database;