const database = {
	tables: {
		chains: [
			{"cid":"2","name":"Cadena anterior de los brazos","image":require("@assets/Cadenas/CADENA_ANTERIOR_DE_LOS_BRAZOS.jpg")},
			{"cid":"3","name":"Cadena posterior de los brazos","image":require("@assets/Cadenas/CADENA_POSTERIOR_DE_LOS_BRAZOS.jpg")},
			{"cid":"4","name":"Cadena posterior superior","image":require("@assets/Cadenas/CADENA_POSTERIOR_SUPERIOR.jpg")},
			{"cid":"5","name":"Cadena posterior inferior","image":require("@assets/Cadenas/CADENA_POSTERIOR_INFERIOR.jpg")},
			{"cid":"6","name":"Cadena anterior","image":require("@assets/Cadenas/CADENA_ANTERIOR.jpg")},
			{"cid":"7","name":"Cuello","image":require("@assets/Cadenas/CUELLO.jpg")},
			{"cid":"8","name":"Cadena lateral","image":require("@assets/Cadenas/CADENA_LATERAL.jpg")}
		],
		exercises: [
			{"eid":"1","name":"Abrazarse","description":"","gif":require("@assets/Ejercicios/ABRAZARSE.mp4"),"cid":"4"},
			{"eid":"2","name":"Alacrán (Izquierda)","description":"","gif":require("@assets/Ejercicios/ALACRAN.mp4"),"cid":"8"},
			{"eid":"3","name":"Alacrán (Derecha)","description":"","gif":require("@assets/Ejercicios/ALACRAN.mp4"),"cid":"8"},
			{"eid":"4","name":"Araña","description":"","gif":require("@assets/Ejercicios/ARAÑA.mp4"),"cid":"6"},
			{"eid":"5","name":"Biceps pero con puño (Izquierda)","description":"","gif":require("@assets/Ejercicios/BICEPS_PERO_CON_PUÑO.mp4"),"cid":"1"},
			{"eid":"6","name":"Biceps pero con puño (Derecha)","description":"","gif":require("@assets/Ejercicios/BICEPS_PERO_CON_PUÑO.mp4"),"cid":"1"},
			{"eid":"7","name":"Bolita","description":"","gif":require("@assets/Ejercicios/BOLITA.mp4"),"cid":"1"},
			{"eid":"8","name":"Cruz (Izquierda)","description":"","gif":require("@assets/Ejercicios/CRUZ.mp4"),"cid":"8"},
			{"eid":"9","name":"Cruz (Derecha)","description":"","gif":require("@assets/Ejercicios/CRUZ.mp4"),"cid":"8"},
			{"eid":"10","name":"Cruzar mano atrás (Izquierda)","description":"","gif":require("@assets/Ejercicios/CRUZAR_MANOS_ATRAS.mp4"),"cid":"1"},
			{"eid":"11","name":"Cruzar mano atrás (Derecha)","description":"","gif":require("@assets/Ejercicios/CRUZAR_MANOS_ATRAS.mp4"),"cid":"1"},
			{"eid":"12","name":"Cruzar un palo (Izquierda)","description":"","gif":require("@assets/Ejercicios/CRUZAR_UN_PALO.mp4"),"cid":"3"},
			{"eid":"13","name":"Cruzar un palo (Derecha)","description":"","gif":require("@assets/Ejercicios/CRUZAR_UN_PALO.mp4"),"cid":"3"},
			{"eid":"14","name":"Cuadriceps levantado el talón (Izquierda)","description":"","gif":require("@assets/Ejercicios/CUADRICEPS_LEVANTADO_EL_TALON.mp4"),"cid":"6"},
			{"eid":"15","name":"Cuadriceps levantado el talón (Derecha)","description":"","gif":require("@assets/Ejercicios/CUADRICEPS_LEVANTADO_EL_TALON.mp4"),"cid":"6"},
			{"eid":"16","name":"Cuadriceps parado (Izquierda)","description":"","gif":require("@assets/Ejercicios/CUADRICEPS_PARADO.mp4"),"cid":"1"},
			{"eid":"17","name":"Cuadriceps parado (Derecha)","description":"","gif":require("@assets/Ejercicios/CUADRICEPS_PARADO.mp4"),"cid":"1"},
			{"eid":"18","name":"Dorsales sentado (Izquierda)","description":"","gif":require("@assets/Ejercicios/DORSALES_SENTADO.mp4"),"cid":"8"},
			{"eid":"19","name":"Dorsales sentado (Derecha)","description":"","gif":require("@assets/Ejercicios/DORSALES_SENTADO.mp4"),"cid":"8"},
			{"eid":"20","name":"Dorsales Y bastón (Izquierda)","description":"","gif":require("@assets/Ejercicios/DORSALES_Y_BASTON.mp4"),"cid":"1"},
			{"eid":"21","name":"Dorsales Y bastón (Derecha)","description":"","gif":require("@assets/Ejercicios/DORSALES_Y_BASTON.mp4"),"cid":"1"},
			{"eid":"22","name":"Enrollarse como una bolita","description":"","gif":require("@assets/Ejercicios/ENROLLARSE_COMO_UNA_BOLITA.mp4"),"cid":"4"},
			{"eid":"23","name":"Entrecruzar pulgares","description":"","gif":require("@assets/Ejercicios/ENTRECRUZAR_PULGARES.mp4"),"cid":"2"},
			{"eid":"24","name":"Flexor de cadera (Izquierda)","description":"","gif":require("@assets/Ejercicios/FLEXOR_DE_CADERA.mp4"),"cid":"1"},
			{"eid":"25","name":"Flexor de cadera (Derecha)","description":"","gif":require("@assets/Ejercicios/FLEXOR_DE_CADERA.mp4"),"cid":"1"},
			{"eid":"26","name":"Gemelos con soga (Izquierda)","description":"","gif":require("@assets/Ejercicios/GEMELOS_CON_SOGA.mp4"),"cid":"1"},
			{"eid":"27","name":"Gemelos con soga (Derecha)","description":"","gif":require("@assets/Ejercicios/GEMELOS_CON_SOGA.mp4"),"cid":"1"},
			{"eid":"28","name":"Gemelos parado (Izquierda)","description":"","gif":require("@assets/Ejercicios/GEMELOS_PARADO.mp4"),"cid":"1"},
			{"eid":"29","name":"Gemelos parado (Derecha)","description":"","gif":require("@assets/Ejercicios/GEMELOS_PARADO.mp4"),"cid":"1"},
			{"eid":"30","name":"Glúteo abrazar la rodilla (Izquierda)","description":"","gif":require("@assets/Ejercicios/GLUTEO_ABRAZAR_LA_RODILLA.mp4"),"cid":"1"},
			{"eid":"31","name":"Glúteo abrazar la rodilla (Derecha)","description":"","gif":require("@assets/Ejercicios/GLUTEO_ABRAZAR_LA_RODILLA.mp4"),"cid":"1"},
			{"eid":"32","name":"El 4 (Izquierda)","description":"","gif":require("@assets/Ejercicios/EL_4.mp4"),"cid":"1"},
			{"eid":"33","name":"El 4 (Derecha)","description":"","gif":require("@assets/Ejercicios/EL_4.mp4"),"cid":"1"},
			{"eid":"34","name":"Hombros cara posterior (Izquierda)","description":"","gif":require("@assets/Ejercicios/HOMBROS_CARA_POSTERIOR.mp4"),"cid":"1"},
			{"eid":"35","name":"Hombros cara anterior (Derecha)","description":"","gif":require("@assets/Ejercicios/HOMBROS_CARA_ANTERIOR.mp4"),"cid":"1"},
			{"eid":"36","name":"Isquio adaptado","description":"","gif":require("@assets/Ejercicios/ISQUIO_ADAPTADO.mp4"),"cid":"1"},
			{"eid":"37","name":"Isquio con soga sentado","description":"","gif":require("@assets/Ejercicios/ISQUIO_CON_SOGA_SENTADO.mp4"),"cid":"1"},
			{"eid":"38","name":"Isquio tirar del pie (Izquierda)","description":"","gif":require("@assets/Ejercicios/ISQUIO_TIRAR_DEL_PIE.mp4"),"cid":"1"},
			{"eid":"39","name":"Isquio tirar del pie (Derecha)","description":"","gif":require("@assets/Ejercicios/ISQUIO_TIRAR_DEL_PIE.mp4"),"cid":"1"},
			{"eid":"40","name":"Rezar","description":"","gif":require("@assets/Ejercicios/REZAR.mp4"),"cid":"1"},
			{"eid":"41","name":"Juntar plantas","description":"","gif":require("@assets/Ejercicios/JUNTAR_PLANTAS.mp4"),"cid":"1"},
			{"eid":"42","name":"Saludo al sol parado","description":"","gif":require("@assets/Ejercicios/SALUDO_AL_SOL_PARADO.mp4"),"cid":"6"},
			{"eid":"43","name":"Mano a la axila (Izquierda)","description":"","gif":require("@assets/Ejercicios/MANO_A_LA_AXILA.mp4"),"cid":"3"},
			{"eid":"44","name":"Mano a la axila (Derecha)","description":"","gif":require("@assets/Ejercicios/MANO_A_LA_AXILA.mp4"),"cid":"3"},
			{"eid":"45","name":"Mano en el cuello","description":"","gif":require("@assets/Ejercicios/MANO_EN_EL_CUELLO.mp4"),"cid":"7"},
			{"eid":"46","name":"Mansalva","description":"","gif":require("@assets/Ejercicios/MANSALVA.mp4"),"cid":"7"},
			{"eid":"47","name":"Mástil (Izquierda)","description":"","gif":require("@assets/Ejercicios/MASTIL.mp4"),"cid":"1"},
			{"eid":"48","name":"Mástil (Derecha)","description":"","gif":require("@assets/Ejercicios/MASTIL.mp4"),"cid":"1"},
			{"eid":"49","name":"Monje","description":"","gif":require("@assets/Ejercicios/MONJE.mp4"),"cid":"1"},
			{"eid":"50","name":"Canastita acostado (Izquierda)","description":"","gif":require("@assets/Ejercicios/CANASTITA_ACOSTADO.mp4"),"cid":"6"},
			{"eid":"51","name":"Canastita acostado (Derecha)","description":"","gif":require("@assets/Ejercicios/CANASTITA_ACOSTADO.mp4"),"cid":"6"},
			{"eid":"52","name":"Pectoral a 120 (Izquierda)","description":"","gif":require("@assets/Ejercicios/PECTORAL_A_120.mp4"),"cid":"1"},
			{"eid":"53","name":"Pectoral a 120 (Derecha)","description":"","gif":require("@assets/Ejercicios/PECTORAL_A_120.mp4"),"cid":"1"},
			{"eid":"54","name":"Pectoral con bastón","description":"","gif":require("@assets/Ejercicios/PECTORAL_CON_BASTON.mp4"),"cid":"2"},
			{"eid":"55","name":"Pectoral en la pared (Izquierda)","description":"","gif":require("@assets/Ejercicios/PECTORAL_EN_LA_PARED.mp4"),"cid":"1"},
			{"eid":"56","name":"Pectoral en la pared (Derecha)","description":"","gif":require("@assets/Ejercicios/PECTORAL_EN_LA_PARED.mp4"),"cid":"1"},
			{"eid":"57","name":"Isquio parado (Izquierda)","description":"","gif":require("@assets/Ejercicios/ISQUIO_PARADO.mp4"),"cid":"5"},
			{"eid":"58","name":"Isquio parado (Derecha)","description":"","gif":require("@assets/Ejercicios/ISQUIO_PARADO.mp4"),"cid":"5"},
			{"eid":"59","name":"Plantares (Izquierda)","description":"","gif":require("@assets/Ejercicios/PLANTARES.mp4"),"cid":"1"},
			{"eid":"60","name":"Plantares (Derecha)","description":"","gif":require("@assets/Ejercicios/PLANTARES.mp4"),"cid":"1"},
			{"eid":"61","name":"Pronación máxima (Izquierda)","description":"","gif":require("@assets/Ejercicios/PRONACION_MAXIMA.mp4"),"cid":"1"},
			{"eid":"62","name":"Pronación máxima (Derecha)","description":"","gif":require("@assets/Ejercicios/PRONACION_MAXIMA.mp4"),"cid":"1"},
			{"eid":"63","name":"Puños al piso","description":"","gif":require("@assets/Ejercicios/PUÑOS_AL_PISO.mp4"),"cid":"3"},
			{"eid":"64","name":"Cruz en L (Izquierda)","description":"","gif":require("@assets/Ejercicios/CRUZ_EN_L.mp4"),"cid":"1"},
			{"eid":"65","name":"Cruz en L (Derecha)","description":"","gif":require("@assets/Ejercicios/CRUZ_EN_L.mp4"),"cid":"1"},
			{"eid":"66","name":"Rotadores (Izquierda)","description":"","gif":require("@assets/Ejercicios/ROTADORES.mp4"),"cid":"1"},
			{"eid":"67","name":"Rotadores (Derecha)","description":"","gif":require("@assets/Ejercicios/ROTADORES.mp4"),"cid":"1"},
			{"eid":"68","name":"Saludo al sol","description":"","gif":require("@assets/Ejercicios/SALUDO_AL_SOL.mp4") ,"cid":"1"},
			{"eid":"69","name":"Sentarse en el talón (Izquierda)","description":"","gif":require("@assets/Ejercicios/SENTARSE_EN_EL_TALON.mp4"),"cid":"1"},
			{"eid":"70","name":"Sentarse en el talón (Derecha)","description":"","gif":require("@assets/Ejercicios/SENTARSE_EN_EL_TALON.mp4"),"cid":"1"},
			{"eid":"71","name":"Sóleo (Izquierda)","description":"","gif":require("@assets/Ejercicios/SOLEO.mp4"),"cid":"1"},
			{"eid":"72","name":"Sóleo (Derecha)","description":"","gif":require("@assets/Ejercicios/SOLEO.mp4"),"cid":"1"},
			{"eid":"73","name":"Dedos al medio","description":"","gif":require("@assets/Ejercicios/DEDOS_AL_MEDIO.mp4"),"cid":"1"},
			{"eid":"74","name":"TFL empujando la rodilla (Izquierda)","description":"","gif":require("@assets/Ejercicios/TFL_EMPUJANDO_LA_RODILLA.mp4"),"cid":"1"},
			{"eid":"75","name":"TFL empujando la rodilla (Derecha)","description":"","gif":require("@assets/Ejercicios/TFL_EMPUJANDO_LA_RODILLA.mp4"),"cid":"1"},
			{"eid":"76","name":"TFL parado (Izquierda)","description":"","gif":require("@assets/Ejercicios/TFL_PARADO.mp4"),"cid":"1"},
			{"eid":"77","name":"TFL parado (Derecha)","description":"","gif":require("@assets/Ejercicios/TFL_PARADO.mp4"),"cid":"1"},
			{"eid":"78","name":"Rodilla afuera (Izquierda)","description":"","gif":require("@assets/Ejercicios/RODILLA_AFUERA.mp4"),"cid":"1"},
			{"eid":"79","name":"Rodilla afuera (Derecha)","description":"","gif":require("@assets/Ejercicios/RODILLA_AFUERA.mp4"),"cid":"1"},
			{"eid":"80","name":"Tirarse dedos para atrás (Izquierda)","description":"","gif":require("@assets/Ejercicios/TIRARSE_DEDOS_PARA_ATRAS.mp4"),"cid":"2"},
			{"eid":"81","name":"Tirarse dedos para atrás (Derecha)","description":"","gif":require("@assets/Ejercicios/TIRARSE_DEDOS_PARA_ATRAS.mp4"),"cid":"2"},
			{"eid":"82","name":"Trapecio sentado (Izquierda)","description":"","gif":require("@assets/Ejercicios/TRAPECIO_SENTADO.mp4"),"cid":"1"},
			{"eid":"83","name":"Trapecio sentado (Derecha)","description":"","gif":require("@assets/Ejercicios/TRAPECIO_SENTADO.mp4"),"cid":"1"},
			{"eid":"84","name":"Triángulo de cadera (Izquierda)","description":"","gif":require("@assets/Ejercicios/TRIANGULO_DE_CADERA.mp4"),"cid":"5"},
			{"eid":"85","name":"Triángulo de cadera (Derecha)","description":"","gif":require("@assets/Ejercicios/TRIANGULO_DE_CADERA.mp4"),"cid":"5"},
			{"eid":"86","name":"Triceps (Izquierda)","description":"","gif":require("@assets/Ejercicios/TRICEPS.mp4"),"cid":"1"},
			{"eid":"87","name":"Triceps (Derecha)","description":"","gif":require("@assets/Ejercicios/TRICEPS.mp4"),"cid":"1"},
			{"eid":"88","name":"Y (Izquierda)","description":"","gif":require("@assets/Ejercicios/Y.mp4"),"cid":"1"},
			{"eid":"89","name":"Y (Derecha)","description":"","gif":require("@assets/Ejercicios/Y.mp4"),"cid":"1"},
			{"eid":"90","name":"Zapo","description":"","gif":require("@assets/Ejercicios/ZAPO.mp4"),"cid":"1"},
		],
		exercises_routines: [
			//GENERAL
			{"erid":"1","rid":"4","eid":"68"},
			{"erid":"2","rid":"4","eid":"7"},
			{"erid":"3","rid":"4","eid":"30"},
			{"erid":"4","rid":"4","eid":"31"},
			{"erid":"5","rid":"4","eid":"37"},
			{"erid":"6","rid":"4","eid":"26"},
			{"erid":"7","rid":"4","eid":"27"},
			{"erid":"8","rid":"4","eid":"49"},
			{"erid":"9","rid":"4","eid":"59"},
			{"erid":"10","rid":"4","eid":"60"},
			{"erid":"11","rid":"4","eid":"71"},
			{"erid":"12","rid":"4","eid":"72"},
			{"erid":"13","rid":"4","eid":"41"},
			{"erid":"14","rid":"4","eid":"90"},
			{"erid":"15","rid":"4","eid":"76"},
			{"erid":"16","rid":"4","eid":"77"},
			{"erid":"17","rid":"4","eid":"24"},
			{"erid":"18","rid":"4","eid":"25"},
			{"erid":"19","rid":"4","eid":"16"},
			{"erid":"20","rid":"4","eid":"17"},
			{"erid":"21","rid":"4","eid":"88"},
			{"erid":"22","rid":"4","eid":"89"},
			{"erid":"23","rid":"4","eid":"34"},
			{"erid":"24","rid":"4","eid":"35"},
			{"erid":"25","rid":"4","eid":"55"},
			{"erid":"26","rid":"4","eid":"56"},
			{"erid":"27","rid":"4","eid":"86"},
			{"erid":"28","rid":"4","eid":"87"},
			{"erid":"29","rid":"4","eid":"82"},
			{"erid":"30","rid":"4","eid":"83"},
			//RUBGBY
			{"erid":"31","rid":"17","eid":"36"},
			{"erid":"32","rid":"17","eid":"69"},
			{"erid":"33","rid":"17","eid":"70"},
			{"erid":"34","rid":"17","eid":"90"},
			{"erid":"35","rid":"17","eid":"35"},
			{"erid":"36","rid":"17","eid":"66"},
			{"erid":"37","rid":"17","eid":"67"},
			{"erid":"38","rid":"17","eid":"7"},
			//TENIS
			{"erid":"39","rid":"11","eid":"54"},
			{"erid":"40","rid":"11","eid":"80"},
			{"erid":"41","rid":"11","eid":"81"},
			{"erid":"42","rid":"11","eid":"40"},
			{"erid":"43","rid":"11","eid":"28"},
			{"erid":"44","rid":"11","eid":"29"},
			{"erid":"45","rid":"11","eid":"59"},
			{"erid":"46","rid":"11","eid":"60"},
			{"erid":"47","rid":"11","eid":"64"},
			{"erid":"48","rid":"11","eid":"65"},
			//BOXEO
			{"erid":"49","rid":"19","eid":"46"},
			{"erid":"50","rid":"19","eid":"54"},
			{"erid":"51","rid":"19","eid":"66"},
			{"erid":"52","rid":"19","eid":"67"},
			{"erid":"53","rid":"19","eid":"59"},
			{"erid":"54","rid":"19","eid":"60"},
			//LEVANTAMIENTO DE PESAS
			{"erid":"55","rid":"12","eid":"32"},
			{"erid":"56","rid":"12","eid":"33"},
			{"erid":"57","rid":"12","eid":"38"},
			{"erid":"58","rid":"12","eid":"39"},
			{"erid":"59","rid":"12","eid":"78"},
			{"erid":"60","rid":"12","eid":"79"},
			{"erid":"61","rid":"12","eid":"71"},
			{"erid":"62","rid":"12","eid":"72"},
			{"erid":"63","rid":"12","eid":"24"},
			{"erid":"64","rid":"12","eid":"25"},
			{"erid":"65","rid":"12","eid":"14"},
			{"erid":"66","rid":"12","eid":"15"},
			{"erid":"67","rid":"12","eid":"23"},
			{"erid":"68","rid":"12","eid":"47"},
			{"erid":"69","rid":"12","eid":"48"},
			//JUDO
			{"erid":"70","rid":"18","eid":"18"},
			{"erid":"71","rid":"18","eid":"19"},
			{"erid":"72","rid":"18","eid":"7"},
			{"erid":"73","rid":"18","eid":"5"},
			{"erid":"74","rid":"18","eid":"6"},
			{"erid":"75","rid":"18","eid":"86"},
			{"erid":"76","rid":"18","eid":"87"},
			{"erid":"77","rid":"18","eid":"14"},
			{"erid":"78","rid":"18","eid":"15"},
			{"erid":"79","rid":"18","eid":"23"},
			//VOLEY
			{"erid":"80","rid":"13","eid":"61"},
			{"erid":"81","rid":"13","eid":"62"},
			{"erid":"82","rid":"13","eid":"45"},
			{"erid":"83","rid":"13","eid":"7"},
			{"erid":"84","rid":"13","eid":"16"},
			{"erid":"85","rid":"13","eid":"17"},
			{"erid":"86","rid":"13","eid":"52"},
			{"erid":"87","rid":"13","eid":"53"},
			//BASQUET
			{"erid":"88","rid":"9","eid":"66"},
			{"erid":"89","rid":"9","eid":"67"},
			{"erid":"90","rid":"9","eid":"30"},
			{"erid":"91","rid":"9","eid":"31"},
			{"erid":"92","rid":"9","eid":"74"},
			{"erid":"93","rid":"9","eid":"75"},
			{"erid":"94","rid":"9","eid":"16"},
			{"erid":"95","rid":"9","eid":"17"},
			{"erid":"96","rid":"9","eid":"41"},
			{"erid":"97","rid":"9","eid":"7"},
			{"erid":"98","rid":"9","eid":"28"},
			{"erid":"99","rid":"9","eid":"29"},
			//HOCKEY
			{"erid":"100","rid":"8","eid":"1"},
			{"erid":"101","rid":"8","eid":"2"},
			{"erid":"102","rid":"8","eid":"3"},
			{"erid":"103","rid":"8","eid":"30"},
			{"erid":"104","rid":"8","eid":"31"},
			{"erid":"105","rid":"8","eid":"38"},
			{"erid":"106","rid":"8","eid":"39"},
			{"erid":"107","rid":"8","eid":"54"},
			{"erid":"108","rid":"8","eid":"28"},
			{"erid":"109","rid":"8","eid":"29"},
			{"erid":"110","rid":"8","eid":"45"},
			//POWER LIFTING
			{"erid":"111","rid":"16","eid":"7"},
			{"erid":"112","rid":"16","eid":"12"},
			{"erid":"113","rid":"16","eid":"13"},
			{"erid":"114","rid":"16","eid":"1"},
			{"erid":"115","rid":"16","eid":"54"},
			{"erid":"116","rid":"16","eid":"24"},
			{"erid":"117","rid":"16","eid":"25"},
			{"erid":"118","rid":"16","eid":"30"},
			{"erid":"119","rid":"16","eid":"31"},
			//NATACIÓN
			{"erid":"120","rid":"14","eid":"54"},
			{"erid":"121","rid":"14","eid":"73"},
			{"erid":"122","rid":"14","eid":"28"},
			{"erid":"123","rid":"14","eid":"29"},
			{"erid":"124","rid":"14","eid":"59"},
			{"erid":"125","rid":"14","eid":"60"},
			//CROSSFIT
			{"erid":"126","rid":"15","eid":"32"},
			{"erid":"127","rid":"15","eid":"33"},
			{"erid":"128","rid":"15","eid":"38"},
			{"erid":"129","rid":"15","eid":"39"},
			{"erid":"130","rid":"15","eid":"78"},
			{"erid":"131","rid":"15","eid":"79"},
			{"erid":"132","rid":"15","eid":"71"},
			{"erid":"133","rid":"15","eid":"72"},
			{"erid":"134","rid":"15","eid":"24"},
			{"erid":"135","rid":"15","eid":"25"},
			{"erid":"136","rid":"15","eid":"14"},
			{"erid":"137","rid":"15","eid":"15"},
			{"erid":"138","rid":"15","eid":"23"},
			{"erid":"139","rid":"15","eid":"47"},
			{"erid":"140","rid":"15","eid":"48"},
			//FUTBOL
			{"erid":"141","rid":"10","eid":"66"},
			{"erid":"142","rid":"10","eid":"67"},
			{"erid":"143","rid":"10","eid":"30"},
			{"erid":"144","rid":"10","eid":"31"},
			{"erid":"145","rid":"10","eid":"74"},
			{"erid":"146","rid":"10","eid":"75"},
			{"erid":"147","rid":"10","eid":"16"},
			{"erid":"148","rid":"10","eid":"17"},
			{"erid":"149","rid":"10","eid":"41"},
			{"erid":"150","rid":"10","eid":"7"},
			{"erid":"151","rid":"10","eid":"28"},
			{"erid":"152","rid":"10","eid":"29"}
		],
		routines: [
			{"rid":"4","type":"general","name":"General","sid":null},
			{"rid":"8","type":"sport","name":"Hockey","sid":"1"},
			{"rid":"9","type":"sport","name":"Básquet","sid":"2"},
			{"rid":"10","type":"sport","name":"Fútbol","sid":"3"},
			{"rid":"11","type":"sport","name":"Tenis","sid":"6"},
			{"rid":"12","type":"sport","name":"Levantamiento de pesas","sid":"7"},
			{"rid":"13","type":"sport","name":"Voley","sid":"8"},
			{"rid":"14","type":"sport","name":"Natación","sid":"9"},
			{"rid":"15","type":"sport","name":"Crossfit","sid":"10"},
			{"rid":"16","type":"sport","name":"Power lifting","sid":"11"},
			{"rid":"17","type":"sport","name":"Rugby","sid":"12"},
			{"rid":"18","type":"sport","name":"Judo","sid":"13"},
			{"rid":"19","type":"sport","name":"Boxeo","sid":"14"},
		],
		sports: [
			{"sid":"1","name":"Hockey"},
			{"sid":"2","name":"Básquet"},
			{"sid":"3","name":"Fútbol"},
			{"sid":"6","name":"Tenis"},
			{"sid":"7","name":"Levantamiento de pesas"},
			{"sid":"8","name":"Voley"},
			{"sid":"9","name":"Natación"},
			{"sid":"10","name":"Crossfit"},
			{"sid":"11","name":"Power lifting"},
			{"sid":"12","name":"Rugby"},
			{"sid":"13","name":"Judo"},
			{"sid":"14","name":"Boxeo"}
		]
	}
}

export default database;