const database = {
	tables: {
		chains: [
			{"cid":"2","name":"Cadena anterior de los brazos","image":require("@assets/Cadenas/CADENA_ANTERIOR_DE_LOS_BRAZOS.jpg")},
			{"cid":"3","name":"Cadena posterior de los brazos","image":require("@assets/Cadenas/CADENA_POSTERIOR_DE_LOS_BRAZOS.jpg")},
			{"cid":"4","name":"Cadena posterior superior","image":require("@assets/Cadenas/CADENA_POSTERIOR_SUPERIOR.jpg")},
			{"cid":"5","name":"Cadena posterior inferior","image":require("@assets/Cadenas/CADENA_POSTERIOR_INFERIOR.jpg")},
			{"cid":"6","name":"Cadena anterior","image":require("@assets/Cadenas/CADENA_ANTERIOR.jpg")},
			{"cid":"7","name":"Cabeza y cuello","image":require("@assets/Cadenas/CABEZA_Y_CUELLO.jpg")},
			{"cid":"1","name":"Cadena lateral","image":require("@assets/Cadenas/CADENA_LATERAL.jpg")}
		],
		exercises: [
			{"eid":"1","name":"Triceps","description":"","gif":require("@assets/Ejercicios/TRICEPS.mp4"),"cid":"1"},
			{"eid":"2","name":"Abrazarse","description":"","gif":require("@assets/Ejercicios/ABRAZARSE.mp4"),"cid":"1"},
			{"eid":"3","name":"Alacrán","description":"","gif":require("@assets/Ejercicios/ALACRAN.mp4"),"cid":"1"},
			{"eid":"4","name":"Araña","description":"","gif":require("@assets/Ejercicios/ARAÑA.mp4"),"cid":"1"},
			{"eid":"5","name":"Biceps pero con puño","description":"","gif":require("@assets/Ejercicios/BICEPS_PERO_CON_PUÑO.mp4"),"cid":"1"},
			{"eid":"6","name":"Bolita","description":"","gif":require("@assets/Ejercicios/BOLITA.mp4"),"cid":"1"},
			{"eid":"7","name":"Cruzar mano atrás","description":"","gif":require("@assets/Ejercicios/CRUZAR_MANOS_ATRAS.mp4"),"cid":"1"},
			{"eid":"8","name":"Cruzar un palo","description":"","gif":require("@assets/Ejercicios/CRUZAR_UN_PALO.mp4"),"cid":"1"},
			{"eid":"9","name":"Cuadriceps levantado el talón","description":"","gif":require("@assets/Ejercicios/CUADRICEPS_LEVANTADO_EL_TALON.mp4"),"cid":"1"},
			{"eid":"10","name":"Cuadriceps parado","description":"","gif":require("@assets/Ejercicios/CUADRICEPS_PARADO.mp4"),"cid":"1"},
			{"eid":"11","name":"Dorsales en la silla sin despegar isquiones","description":"","gif":require("@assets/Ejercicios/DORSALES_EN_LA_SILLA_SIN_DESPEGAR_ISQUIONES.mp4"),"cid":"1"},
			{"eid":"12","name":"Dorsales y bastón","description":"","gif":require("@assets/Ejercicios/DORSALES_Y_BASTON.mp4"),"cid":"1"},
			{"eid":"13","name":"El que filme con lucho","description":"","gif":require("@assets/Ejercicios/EL_QUE_FILME_CON_LUCHO.mp4"),"cid":"1"},
			{"eid":"14","name":"Enrollarse como una bolita","description":"","gif":require("@assets/Ejercicios/ENROLLARSE_COMO_UNA_BOLITA.mp4"),"cid":"1"},
			{"eid":"15","name":"Entrecruzar pulgares","description":"","gif":require("@assets/Ejercicios/ENTRECRUZAR_PULGARES.mp4"),"cid":"1"},
			{"eid":"16","name":"Flexor de cadera","description":"","gif":require("@assets/Ejercicios/FLEXOR_DE_CADERA.mp4"),"cid":"1"},
			{"eid":"17","name":"Gemelos con soga","description":"","gif":require("@assets/Ejercicios/GEMELOS_CON_SOGA.mp4"),"cid":"1"},
			{"eid":"18","name":"Gemelos parado","description":"","gif":require("@assets/Ejercicios/GEMELOS_PARADO.mp4"),"cid":"1"},
			{"eid":"19","name":"Glúteo abrazar la rodilla","description":"","gif":require("@assets/Ejercicios/GLUTEO_ABRAZAR_LA_RODILLA.mp4"),"cid":"1"},
			{"eid":"20","name":"Glúteo agacharse","description":"","gif":require("@assets/Ejercicios/GLUTEO_AGACHARSE.mp4"),"cid":"1"},
			{"eid":"21","name":"Hombros para adelante","description":"","gif":require("@assets/Ejercicios/HOMBROS_PARA_ADELANTE.mp4"),"cid":"1"},
			{"eid":"22","name":"Hombros para atrás","description":"","gif":require("@assets/Ejercicios/HOMBROS_PARA_ATRAS.mp4"),"cid":"1"},
			{"eid":"23","name":"Isquio como hacíamos con sandri","description":"","gif":require("@assets/Ejercicios/ISQUIO_COMO_HACIAMOS_CON_SANDRI.mp4"),"cid":"1"},
			{"eid":"24","name":"Isquio con soga sentado","description":"","gif":require("@assets/Ejercicios/ISQUIO_CON_SOGA_SENTADO.mp4"),"cid":"1"},
			{"eid":"25","name":"Isquio tirar del pie","description":"","gif":require("@assets/Ejercicios/ISQUIO_TIRAR_DEL_PIE.mp4"),"cid":"1"},
			{"eid":"26","name":"Juntar dorso de la mano","description":"","gif":require("@assets/Ejercicios/JUNTAR_DORSO_DE_LA_MANO.mp4"),"cid":"1"},
			{"eid":"27","name":"Juntar plantas","description":"","gif":require("@assets/Ejercicios/JUNTAR_PLANTAS.mp4"),"cid":"1"},
			{"eid":"28","name":"La foto del final","description":"","gif":require("@assets/Ejercicios/LA_FOTO_DEL_FINAL.mp4"),"cid":"1"},
			{"eid":"29","name":"Mano a la axila","description":"","gif":require("@assets/Ejercicios/MANO_A_LA_AXILA.mp4"),"cid":"1"},
			{"eid":"30","name":"Mano en el cuello","description":"","gif":require("@assets/Ejercicios/MANO_EN_EL_CUELLO.mp4"),"cid":"1"},
			{"eid":"31","name":"Mansalva","description":"","gif":require("@assets/Ejercicios/MANSALVA.mp4"),"cid":"1"},
			{"eid":"32","name":"Mástil","description":"","gif":require("@assets/Ejercicios/MASTIL.mp4"),"cid":"1"},
			{"eid":"33","name":"Monje","description":"","gif":require("@assets/Ejercicios/MONJE.mp4"),"cid":"1"},
			{"eid":"34","name":"Muchos almohadones en el sacro","description":"","gif":require("@assets/Ejercicios/MUCHOS_ALMOHADONES_EN_EL_SACRO.mp4"),"cid":"1"},
			{"eid":"35","name":"Pectoral a 120","description":"","gif":require("@assets/Ejercicios/PECTORAL_A_120.mp4"),"cid":"1"},
			{"eid":"36","name":"Pectoral con bastón","description":"","gif":require("@assets/Ejercicios/PECTORAL_CON_BASTON.mp4"),"cid":"1"},
			{"eid":"37","name":"Pectoral en la pared","description":"","gif":require("@assets/Ejercicios/PECTORAL_EN_LA_PARED.mp4"),"cid":"1"},
			{"eid":"38","name":"Pie en el marco de la puerta","description":"","gif":require("@assets/Ejercicios/PIE_EN_EL_MARCO_DE_LA_PUERTA.mp4"),"cid":"1"},
			{"eid":"39","name":"Plantares de los dedos","description":"","gif":require("@assets/Ejercicios/PLANTARES_DE_LOS_DEDOS.mp4"),"cid":"1"},
			{"eid":"40","name":"Pronación máxima","description":"","gif":require("@assets/Ejercicios/PRONACION_MAXIMA.mp4"),"cid":"1"},
			{"eid":"41","name":"Puños al piso","description":"","gif":require("@assets/Ejercicios/PUÑOS_AL_PISO.mp4"),"cid":"1"},
			{"eid":"42","name":"Rotador de lucho","description":"","gif":require("@assets/Ejercicios/ROTADOR_DE_LUCHO.mp4"),"cid":"1"},
			{"eid":"43","name":"Rotar en la silla tomándose del respaldar","description":"","gif":require("@assets/Ejercicios/ROTAR_EN_LA_SILLA_TOMANDOSE_DEL_RESPALDAR.mp4"),"cid":"1"},
			{"eid":"44","name":"Saludo al sol","description":"","gif":require("@assets/Ejercicios/SALUDO_AL_SOL.mp4") ,"cid":"1"},
			{"eid":"45","name":"Sentarse en el talón","description":"","gif":require("@assets/Ejercicios/SENTARSE_EN_EL_TALON.mp4"),"cid":"1"},
			{"eid":"46","name":"Soleo","description":"","gif":require("@assets/Ejercicios/SOLEO.mp4"),"cid":"1"},
			{"eid":"47","name":"Supinación en un libro","description":"","gif":require("@assets/Ejercicios/SUPINACION_EN_UN_LIBRO.mp4"),"cid":"1"},
			{"eid":"48","name":"TFL empujando la rodilla","description":"","gif":require("@assets/Ejercicios/TFL_EMPUJANDO_LA_RODILLA.mp4"),"cid":"1"},
			{"eid":"49","name":"TFL parado","description":"","gif":require("@assets/Ejercicios/TFL_PARADO.mp4"),"cid":"1"},
			{"eid":"50","name":"Tirarse dedos atrás pie","description":"","gif":require("@assets/Ejercicios/TIRARSE_DEDOS_ATRAS_PIE.mp4"),"cid":"1"},
			{"eid":"51","name":"Tirarse dedos atrás","description":"","gif":require("@assets/Ejercicios/TIRARSE_DEDOS_ATRAS.mp4"),"cid":"1"},
			{"eid":"52","name":"Trapecio sentado","description":"","gif":require("@assets/Ejercicios/TRAPECIO_SENTADO.mp4"),"cid":"1"},
			{"eid":"53","name":"Triángulo de cadera","description":"","gif":require("@assets/Ejercicios/TRIANGULO_DE_CADERA.mp4"),"cid":"1"},
			{"eid":"54","name":"Y","description":"","gif":require("@assets/Ejercicios/Y.mp4"),"cid":"1"},
			{"eid":"55","name":"Zapo","description":"","gif":require("@assets/Ejercicios/ZAPO.mp4"),"cid":"1"},
		],
		exercises_routines: [
			{"erid":"121","rid":"6","eid":"44","description":"20\" trabajo x 10\" pausa","replays":"3","seconds":"20"},
			{"erid":"120","rid":"6","eid":"6","description":"20\" trabajo x 10\" pausa","replays":"3","seconds":"20"},
			{"erid":"119","rid":"6","eid":"19","description":"20\" trabajo x 10\" pausa","replays":"3","seconds":"20"},
			{"erid":"118","rid":"6","eid":"17","description":"20\" trabajo x 10\" pausa","replays":"3","seconds":"20"},
			{"erid":"117","rid":"6","eid":"33","description":"20\" trabajo x 10\" pausa","replays":"3","seconds":"20"},
			{"erid":"116","rid":"6","eid":"27","description":"20\" trabajo x 10\" pausa","replays":"3","seconds":"20"},
			{"erid":"115","rid":"6","eid":"46","description":"20\" trabajo x 10\" pausa","replays":"3","seconds":"20"},
			{"erid":"114","rid":"6","eid":"37","description":"20\" trabajo x 10\" pausa","replays":"3","seconds":"20"},
			{"erid":"113","rid":"6","eid":"55","description":"20\" trabajo x 10\" pausa","replays":"3","seconds":"20"},
			{"erid":"112","rid":"6","eid":"49","description":"20\" trabajo x 10\" pausa","replays":"3","seconds":"20"},
			{"erid":"111","rid":"6","eid":"35","description":"20\" trabajo x 10\" pausa","replays":"3","seconds":"20"},
			{"erid":"110","rid":"6","eid":"10","description":"20\" trabajo x 10\" pausa","replays":"3","seconds":"20"},
			{"erid":"109","rid":"6","eid":"54","description":"20\" trabajo x 10\" pausa","replays":"3","seconds":"20"},
			{"erid":"108","rid":"6","eid":"21","description":"20\" trabajo x 10\" pausa","replays":"3","seconds":"20"},
			{"erid":"107","rid":"6","eid":"22","description":"20\" trabajo x 10\" pausa","replays":"3","seconds":"20"},
			{"erid":"106","rid":"6","eid":"37","description":"20\" trabajo x 10\" pausa","replays":"3","seconds":"20"},
			{"erid":"105","rid":"6","eid":"1","description":"20\" trabajo x 10\" pausa","replays":"3","seconds":"20"},
			{"erid":"104","rid":"6","eid":"52","description":"20\" trabajo x 10\" pausa","replays":"3","seconds":"20"},
			{"erid":"101","rid":"5","eid":"44","description":"20\" trabajo x 10\" pausa","replays":"2","seconds":"20"},
			{"erid":"100","rid":"5","eid":"6","description":"20\" trabajo x 10\" pausa","replays":"2","seconds":"20"},
			{"erid":"99","rid":"5","eid":"19","description":"20\" trabajo x 10\" pausa","replays":"2","seconds":"20"},
			{"erid":"98","rid":"5","eid":"17","description":"20\" trabajo x 10\" pausa","replays":"2","seconds":"20"},
			{"erid":"97","rid":"5","eid":"33","description":"20\" trabajo x 10\" pausa","replays":"2","seconds":"20"},
			{"erid":"96","rid":"5","eid":"27","description":"20\" trabajo x 10\" pausa","replays":"2","seconds":"20"},
			{"erid":"95","rid":"5","eid":"46","description":"20\" trabajo x 10\" pausa","replays":"2","seconds":"20"},
			{"erid":"94","rid":"5","eid":"37","description":"20\" trabajo x 10\" pausa","replays":"2","seconds":"20"},
			{"erid":"93","rid":"5","eid":"55","description":"20\" trabajo x 10\" pausa","replays":"2","seconds":"20"},
			{"erid":"92","rid":"5","eid":"49","description":"20\" trabajo x 10\" pausa","replays":"2","seconds":"20"},
			{"erid":"91","rid":"5","eid":"35","description":"20\" trabajo x 10\" pausa","replays":"2","seconds":"20"},
			{"erid":"90","rid":"5","eid":"10","description":"20\" trabajo x 10\" pausa","replays":"2","seconds":"20"},
			{"erid":"89","rid":"5","eid":"54","description":"20\" trabajo x 10\" pausa","replays":"2","seconds":"20"},
			{"erid":"88","rid":"5","eid":"21","description":"20\" trabajo x 10\" pausa","replays":"2","seconds":"20"},
			{"erid":"87","rid":"5","eid":"22","description":"20\" trabajo x 10\" pausa","replays":"2","seconds":"20"},
			{"erid":"86","rid":"5","eid":"37","description":"20\" trabajo x 10\" pausa","replays":"2","seconds":"20"},
			{"erid":"85","rid":"5","eid":"1","description":"20\" trabajo x 10\" pausa","replays":"2","seconds":"20"},
			{"erid":"84","rid":"5","eid":"52","description":"20\" trabajo x 10\" pausa","replays":"2","seconds":"20"},
			{"erid":"81","rid":"4","eid":"44","description":"20\" trabajo x 10\" pausa","replays":"1","seconds":"20"},
			{"erid":"80","rid":"4","eid":"6","description":"20\" trabajo x 10\" pausa","replays":"1","seconds":"20"},
			{"erid":"79","rid":"4","eid":"19","description":"20\" trabajo x 10\" pausa","replays":"1","seconds":"20"},
			{"erid":"78","rid":"4","eid":"17","description":"20\" trabajo x 10\" pausa","replays":"1","seconds":"20"},
			{"erid":"77","rid":"4","eid":"33","description":"20\" trabajo x 10\" pausa","replays":"1","seconds":"20"},
			{"erid":"76","rid":"4","eid":"27","description":"20\" trabajo x 10\" pausa","replays":"1","seconds":"20"},
			{"erid":"75","rid":"4","eid":"46","description":"20\" trabajo x 10\" pausa","replays":"1","seconds":"20"},
			{"erid":"74","rid":"4","eid":"37","description":"20\" trabajo x 10\" pausa","replays":"1","seconds":"20"},
			{"erid":"73","rid":"4","eid":"55","description":"20\" trabajo x 10\" pausa","replays":"1","seconds":"20"},
			{"erid":"72","rid":"4","eid":"49","description":"20\" trabajo x 10\" pausa","replays":"1","seconds":"20"},
			{"erid":"71","rid":"4","eid":"35","description":"20\" trabajo x 10\" pausa","replays":"1","seconds":"20"},
			{"erid":"70","rid":"4","eid":"10","description":"20\" trabajo x 10\" pausa","replays":"1","seconds":"20"},
			{"erid":"69","rid":"4","eid":"54","description":"20\" trabajo x 10\" pausa","replays":"1","seconds":"20"},
			{"erid":"68","rid":"4","eid":"21","description":"20\" trabajo x 10\" pausa","replays":"1","seconds":"20"},
			{"erid":"67","rid":"4","eid":"22","description":"20\" trabajo x 10\" pausa","replays":"1","seconds":"20"},
			{"erid":"66","rid":"4","eid":"37","description":"20\" trabajo x 10\" pausa","replays":"1","seconds":"20"},
			{"erid":"65","rid":"4","eid":"1","description":"20\" trabajo x 10\" pausa","replays":"1","seconds":"20"},
			{"erid":"64","rid":"4","eid":"52","description":"20\" trabajo x 10\" pausa","replays":"1","seconds":"20"}
		],
		routines: [
			{"rid":"4","type":"general","repetitions": 1,"name":"Nivel 1","sid":null},
			{"rid":"5","type":"general","repetitions": 2,"name":"Nivel 2","sid":null},
			{"rid":"6","type":"general","repetitions": 3,"name":"Nivel 3","sid":null},
			{"rid":"8","type":"sport","repetitions": 1,"name":"Hockey","sid":"1"},
			{"rid":"9","type":"sport","repetitions": 1,"name":"Básquet","sid":"2"},
			{"rid":"10","type":"sport","repetitions": 1,"name":"Fútbol","sid":"3"},
			{"rid":"11","type":"sport","repetitions": 1,"name":"Tenis","sid":"6"},
			{"rid":"12","type":"sport","repetitions": 1,"name":"Levantamiento de pesas","sid":"7"},
			{"rid":"13","type":"sport","repetitions": 1,"name":"Voley","sid":"8"},
			{"rid":"14","type":"sport","repetitions": 1,"name":"Natación","sid":"9"},
			{"rid":"15","type":"sport","repetitions": 1,"name":"Crossfit","sid":"10"},
			{"rid":"16","type":"sport","repetitions": 1,"name":"Power lifting","sid":"11"},
			{"rid":"17","type":"sport","repetitions": 1,"name":"Rugby","sid":"12"},
			{"rid":"18","type":"sport","repetitions": 1,"name":"Judo","sid":"13"},
			{"rid":"19","type":"sport","repetitions": 1,"name":"Boxeo","sid":"14"}
		],
		sports: [
			{"sid":"1","name":"Hockey"},
			{"sid":"2","name":"Básquet"},
			{"sid":"3","name":"Fútbol"},
			{"sid":"6","name":"Tenis"},
			{"sid":"7","name":"Levantamiento de pesas"},
			{"sid":"8","name":"Voley"},
			{"sid":"9","name":"Natación"},
			{"sid":"10","name":"Crossfit"},
			{"sid":"11","name":"Power lifting"},
			{"sid":"12","name":"Rugby"},
			{"sid":"13","name":"Judo"},
			{"sid":"14","name":"Boxeo"}
		]
	}
}

export default database;